7 Location Search
NYCPlanning/ae-zoning-map-poc pull request #10
Opened 2023-11-03 15:47 UTC by dhochbaum-dcp

Incomplete, but stubbed out.

2023-11-03 16:07 UTC, TylerMatteo requested changes

2023-11-03 16:07 UTC, TylerMatteo commented on src/components/LocationSearch.tsx
> +            <Box>
A `FormControl` represents a given input within a form and it's associated components, such as the label and error message. Therefore, you should actually have three of them here, effectively replacing where you have these boxes. If you want to wrap the collection of them in a `<form>`, that would be great.

2023-11-03 16:07 UTC, TylerMatteo commented on src/components/LocationSearch.tsx
> +          <Box flexDirection={"row"} display={"flex"} gap={5} pt={3}>
Just fyi, Streetscape exports several convenience layout components from Chakra that can simplify this sort of think, such as [Flex](https://chakra-ui.com/docs/components/flex), [Stack](https://chakra-ui.com/docs/components/stack), HStack, VStack, etc.

2023-11-03 16:07 UTC, TylerMatteo commented on src/components/LocationSearch.tsx
> +          <Input placeholder="Replace this with Select when it has been merged" />
I just release Streetscape v0.8.0 which has your Select so you can drop that in now.

2023-11-03 16:07 UTC, TylerMatteo commented on src/components/LocationSearch.tsx
> +      p={"4 4 6 4"}
Are you sure this works? I don't think Chakra is smart enough to parse this but I could be wrong. The alternative would be
```
pt={4} // note this is the number 4, not a string
pb={6}
px={4}
```

2023-11-06 20:15 UTC, dhochbaum-dcp commented on src/components/LocationSearch.tsx
> +      p={"4 4 6 4"}
You are correct, it does not.

2023-11-06 20:18 UTC, dhochbaum-dcp commented on src/components/LocationSearch.tsx
> +    <AccordionItem
Did not move AccordionItem - I needed its internal state property `isExpanded` to change the icon.

2023-11-06 21:42 UTC, TylerMatteo commented on src/components/LocationSearch.tsx
> +    <AccordionItem
Ah, I see. And you can't use `AccordionIcon` because these ones have a different icon than the rest of them. We'll need to sort this out when we get around to doing mobile this is a good enough reason to punt for now. Resolving.

2023-11-13 13:50 UTC, TylerMatteo approved these changes

2023-11-13 13:50 UTC, merged