15183-4 map controls
NYCPlanning/ae-zoning-map-poc pull request #2
Opened 2023-10-11 19:33 UTC by dhochbaum-dcp

<img width="1717" alt="image" src="https://github.com/NYCPlanning/ae-zoning-map-poc/assets/61206501/a9585991-963b-46fe-b4cd-18e1c72d9de0">

Draws basic map and map controls.

Completes tasks AB#15183 and AB#15184; also completes their corresponding user stories AB#14931 and AB#15160.

2023-10-12 14:47 UTC, TylerMatteo requested changes

2023-10-12 14:47 UTC, TylerMatteo commented on src/App.tsx
> +          position={CONFIG.NAVIGATION.POSITION as ControlPosition}
You can just set these props on `NavigationControl` in-line here instead of referencing `CONFIG`, so this point is maybe moot, but it's a teachable Typescript moment: if you find yourself casting with `as`, it's probably a hint that you should be typing something where it's being defined. In this case, you might do
```
import type { ControlPosition } from "maplibre-gl";
export const POSITION: ControlPosition = "bottom-left";
```

2023-10-12 20:43 UTC, dhochbaum-dcp commented on src/App.tsx
> +    <Map
Implemented.

2023-10-12 20:54 UTC, dhochbaum-dcp commented on src/config.ts
I had assumed we wanted maximum flexibility, where we could deploy a new map as a site or even a route simply by editing a config file.  I have updated the code to set the variables directly in App.tsx.

2023-10-13 15:58 UTC, TylerMatteo requested changes

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.tsx
> +        style={{ width: width, height: height }}
Can you try setting these as `"100vw"` and `"100vh"`, respectively? I've seen examples that do that and it would be better to use those CSS values than rely on a hook that has to update the values dynamically.

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.tsx
> +        maxBounds={[
Let's try controlling min and max bounds via the onViewStateChange handler of the `<DeckGL>` component. [These docs](https://deck.gl/docs/developer-guide/interactivity#add-constraints-to-view-state) show an example of how to do that.

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.tsx
> +    bearing: 0,
You can set `minZoom`, `maxZoom`, `minPitch`, and `maxPitch` here instead of on `<Map>`. The pitch ones will satisfy the requirement of not allowing the using to adjust the pitch. I think it will be better for us in the long run to get into the habit of setting these things on the `<DeckGL>` component instead of `<Map>`, which ultimately just corresponds to the basemap.

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.tsx
> +            unit="imperial" //'imperial' | 'metric' | 'nautical'
You don't need to remove these comments but just some advise for how I approach commenting - I tend not to add comments when the dependencies we use already provide good built-in descriptions. In this case, hovering over these props in VSCode shows descriptions that come from `react-map-gl`.
![image](https://github.com/NYCPlanning/ae-zoning-map-poc/assets/9055367/8b9657a7-a4c4-42d3-83ea-97013eb3f9be)
![image](https://github.com/NYCPlanning/ae-zoning-map-poc/assets/9055367/591395e3-b265-43cd-8600-b9a9e54572fb)

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.css
> +.maplibregl-ctrl-bottom-right .maplibregl-ctrl-group {
Leaving a comment to remind us to refactor this once we integrate Chakra into this project.

2023-10-13 15:58 UTC, TylerMatteo commented on package.json
> +    "@danmarshall/deckgl-typings": "^4.9.28",
Try uninstalling this and see if the typings still work. Deck has types build in as of version 8.8 so I don't think you should need it.

2023-10-13 15:58 UTC, TylerMatteo commented on src/App.tsx
> +import DeckGL from "@deck.gl/react";
Tweak these imports to pull in the[ typed versions of the component](https://deck.gl/docs/get-started/using-with-typescript).

2023-10-13 18:01 UTC, dhochbaum-dcp commented on src/App.tsx
> +import DeckGL from "@deck.gl/react";
I was able to do so for Deck, but I'm not sure how to import the typed version of window size, and I'm not sure what it would mean to do so.

2023-10-13 19:03 UTC, TylerMatteo commented on src/App.tsx
> +import DeckGL from "@deck.gl/react";
The `useWindowSize` you're importing is already typed. Having to import from a path with `/typed` on the end isn't a general Typescript thing, it's something you have to do for Deck specifically. They added types but wanted to build in a way for users to opt in or out of them, so they put typed stuff under a folder that just happens to be called `typed`. In a future version of Deck, there will probably just be `@deck.gl/react` and everything will be typed by default.

2023-10-19 20:22 UTC, TylerMatteo approved these changes
Lgtm. Leaving some notes about things we should refactor once `@nycplanning/streetscape` is integrated:
* Use Chakra responsive utils to remove dep on `useWindowWidth`
* Move all styling to leverage Chakra, such that we can delete the App.css

2023-10-19 20:22 UTC, merged