17 Add Zoning District detail panel (Desktop)
NYCPlanning/ae-zoning-map-poc pull request #36
Opened 2023-12-14 22:56 UTC by dhochbaum-dcp

Completes #17 

Refactored some items and added the zoning district detail panel.

Clicking on the map and viewing the zoning district detail panel will not work until the map tile UUIDs are updated to match the ids in the zoning_district db table (or vice versa).  In the meantime, you can test the zoning district detail panel by replacing line 117 in App.tsx with the contents of line 118 (for a single district selection) or 119 (for a multiple district selection).

2023-12-18 19:48 UTC, TylerMatteo requested changes

2023-12-18 19:48 UTC, TylerMatteo commented on src/store/index.ts
> +  infoPane: "",
If we're going to use strings to keep track of state that is always one of a pre-determined set of values, we should type it as such and avoid using empty strings as one of the values. You can use [unioned TS literal types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types) or even [enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) to accomplish this. The type can also include `null` to be used when no options is selected, instead of an empty string.

2023-12-18 19:48 UTC, TylerMatteo commented on src/components/ZoningDistrictDetails.tsx
> +        {zds.map((district) => (
I think you could replace this with `Array.from(zoningDistrictClasses).map` and get rid of that interstitial variable on line 16

2023-12-19 14:29 UTC, dhochbaum-dcp commented on src/components/ZoningDistrictDetails.tsx
> +        {zds.map((district) => (
Updated.  Is there a difference in performance between the interstitial variable and using Array.from() twice?

2023-12-19 14:29 UTC, dhochbaum-dcp commented on src/store/index.ts
> +  infoPane: "",
Updated.

2023-12-19 14:29 UTC, dhochbaum-dcp commented on src/App.tsx
> +  const [selectedZoningDistrictClasses, setSelectedZoningDistrictClasses] =
Updated.

2023-12-19 21:01 UTC, TylerMatteo requested changes

2023-12-19 21:01 UTC, TylerMatteo commented on src/App.tsx
> +      // setSelectedZoningDistrictUuid('0025a136-64fe-4838-bdf2-c3d3f80634cd')
Is the UUID mismatch issue fixed with the re-uploaded data we got from DE? It would be great to get these hard coded uuids out of here before merging if we can.

2023-12-19 21:05 UTC, dhochbaum-dcp commented on src/App.tsx
> +      // setSelectedZoningDistrictUuid('0025a136-64fe-4838-bdf2-c3d3f80634cd')
They will be re-uploaded tomorrow.  I have now removed them.

2023-12-20 14:53 UTC, TylerMatteo approved these changes

2023-12-20 14:53 UTC, TylerMatteo commented on src/App.tsx
> +  const { data: zoningDistrictClasses } = useGetZoningDistrictClassesByUuid(
Just making a note to revisit refactoring this in the future:

I was picturing we could do nesting destructuring here like `const { data: { zoningDistrictClasses } } = useGet....` but typescript complains about that, apparently because that value could also be undefined. Doing the nested destructuring would be nice because we can avoid confusing lines like ln 217 where you have `new Set(zoningDistrictClasses?.zoningDistrictClasses)`. I'm approving this PR, but this would be nice to revisit.

2023-12-20 14:59 UTC, merged