14/tax lot layers toggle
NYCPlanning/ae-zoning-map-poc pull request #39
Opened 2024-01-02 19:36 UTC by bmarchena

This PR adds Tax Lots layer and filter functionality.

Final outstanding issue is Tax Lot boundaries displaying when the Tax Lots layer is on, regardless of the state of the filter. I've attempted to override the layer's getLineColor function to accurately reflect the state but have been unsuccessful.

2024-01-03 15:44 UTC, TylerMatteo requested changes

2024-01-03 15:44 UTC, TylerMatteo commented on src/components/TaxLotFilters.tsx
> +            if (anyTaxLotsVisibility) toggleVisibleTaxLotsBoundaries();
Do you need `if (anyTaxLotsVisibility)` here? This whole component is hidden if that bool is false, so I don't think you need to check again here. Same goes for line 48.

2024-01-03 15:44 UTC, TylerMatteo commented on src/App.tsx
> +      let color = undefined;
I think the solution here is actually to return `[0, 0, 0, 0]` when you want the boundaries to be hidden and `[0, 0, 0]` when you want them to be shown. Deck accepts an optional fourth number for "alpha" (aka opacity) when specifying these rgba arrays. Can you give that a try?

2024-01-03 15:46 UTC, TylerMatteo requested changes

2024-01-03 15:46 UTC, TylerMatteo commented on src/App.tsx
> +  const taxLotsLayer = new MVTLayer({
You can add some params here to render the tax lot's "lot" number as the label on the map, borrowing this code from the zoning districts layer:
```
pointType: "text",
    getText: (f: any) => f.properties.district,
    getTextColor: [98, 98, 98, 255],
    textFontFamily: "Helvetica Neue, Arial, sans-serif",
    getTextSize: 8,
```
The value you want should be on `f.properties.lot`

2024-01-04 15:37 UTC, bmarchena commented on src/App.tsx
> +      let color = undefined;
That did it, thanks

2024-01-04 19:47 UTC, TylerMatteo approved these changes

2024-01-04 21:26 UTC, merged